### ISSUE TITLE
Prepare APIM 4.2.0 regression scenarios document for QA

### ISSUE THREAD

**Issue by vishmi49** [wso2-incubator/apim-test-integration#195]
**Description:**
Prepare APIM 4.2.0 regression scenarios doc for QA

**Affected Product Version:**
- 4.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vishmi49** [comment]
Task keep on hold to to commit to another task

**Comment by nandika** [comment]
Closing this issue since 4.2.0 release is completed long time ago
